name: amigos
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  intl_phone_number_input: ^0.7.0+2
  pin_code_fields: ^7.3.0

  shared_preferences: ^2.0.7
  get: ^4.3.8
  google_fonts: ^2.1.0
  provider: ^6.0.0
  smooth_page_indicator: ^1.0.0+2
  step_progress_indicator: ^1.0.1
  percent_indicator: ^3.4.0
  image_picker: ^0.8.4+4
  cached_network_image: ^3.2.0
  flutter_chat_bubble: ^2.0.0
  swipable_stack: ^0.8.1
  carousel_slider: ^4.0.0
  expandable: ^5.0.1
  syncfusion_flutter_sliders: ^19.4.40
  flutter_slidable: ^1.2.0
  dotted_line: ^3.1.0
  dio: ^4.0.4
  google_maps_flutter: ^2.1.1
  geolocator: ^8.0.1
  geocode: ^1.0.1
    #  google_maps_webservice: ^0.0.19
  google_maps_webservice: ^0.0.20-nullsafety.5
  google_places_flutter: ^2.0.5
  location: ^4.3.0
  http: ^0.13.4
  geocoding: ^2.0.1
  flutter_map: ^0.14.0
  flutter_polyline_points: ^1.0.0
  animated_bottom_navigation_bar: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/crewluv_app_launcher.png"


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/translations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
